GEAR_DEFAULT = 0
GEAR_HIGH_BOOSTER = 1
GEAR_AUTO_SLIDER = 2
GEAR_POWERFUL = 3
GEAR_FASTEST = 4
GEAR_TURBO_STAR = 5
GEAR_SPEED_BALANCER = 6
GEAR_BLUE_STAR_II = 7
GEAR_ACCESS = 8
GEAR_BEGINNER = 9
GEAR_ACCELERATOR = 10
GEAR_TRAP = 11
GEAR_LIGHT_BOARD = 12
GEAR_SLIDE_BOOSTER = 13
GEAR_LEGEND = 14
GEAR_MAGIC_CARPET = 15
GEAR_AIR_BROOM = 16
GEAR_HOVERCRAFT = 17
GEAR_CHAOS_EMERALD = 18
GEAR_FASTER = 19
GEAR_GAMBLER = 20
GEAR_POWER = 21
GEAR_OPA_OPA = 22
GEAR_CRAZY = 23
GEAR_BERSERKER = 24
GEAR_E_RIDER = 25  # Eggman Default Gear
GEAR_AIR_TANK = 26
GEAR_HEAVY_BIKE = 27
GEAR_DESTROYER = 28
GEAR_OMNIPOTENCE = 29
GEAR_COVER_S = 30
GEAR_COVER_F = 31
GEAR_COVER_P = 32
GEAR_HANG_ON = 33
GEAR_SUPER_HANG_ON = 34
GEAR_DARKNESS = 35  # Shadow Default Gear
GEAR_GRINDER = 36
GEAR_ADVANTAGE_S = 37
GEAR_ADVANTAGE_F = 38
GEAR_ADVANTAGE_P = 39
GEAR_CANNONBALL = 40

GEAR_ID_TO_NAME = {
    GEAR_DEFAULT: "Default Gear",
    GEAR_HIGH_BOOSTER: "High Booster",
    GEAR_AUTO_SLIDER: "Auto Slider",
    GEAR_POWERFUL: "Powerful Gear",
    GEAR_FASTEST: "Fastest",
    GEAR_TURBO_STAR: "Turbo Star",
    GEAR_SPEED_BALANCER: "Speed Balancer",
    GEAR_BLUE_STAR_II: "Blue Star II",
    GEAR_ACCESS: "Access",
    GEAR_BEGINNER: "Beginner",
    GEAR_ACCELERATOR: "Accelerator",
    GEAR_TRAP: "Trap Gear",
    GEAR_LIGHT_BOARD: "Light Board",
    GEAR_SLIDE_BOOSTER: "Slide Booster",
    GEAR_LEGEND: "Legend",
    GEAR_MAGIC_CARPET: "Magic Carpet",
    GEAR_AIR_BROOM: "Air Broom",
    GEAR_HOVERCRAFT: "Hovercraft",
    GEAR_CHAOS_EMERALD: "Super Sonic",
    GEAR_FASTER: "Faster",
    GEAR_GAMBLER: "Gambler",
    GEAR_POWER: "Power Gear",
    GEAR_OPA_OPA: "Opa Opa",
    GEAR_CRAZY: "The Crazy",
    GEAR_BERSERKER: "Berserker",
    GEAR_E_RIDER: "E-Rider",
    GEAR_AIR_TANK: "Air Tank",
    GEAR_HEAVY_BIKE: "Heavy Bike",
    GEAR_DESTROYER: "Destroyer",
    GEAR_OMNIPOTENCE: "Omnipotence",
    GEAR_COVER_S: "Cover-S",
    GEAR_COVER_F: "Cover-F",
    GEAR_COVER_P: "Cover-P",
    GEAR_HANG_ON: "Hang-On",
    GEAR_SUPER_HANG_ON: "Super Hang-On",
    GEAR_DARKNESS: "Darkness",
    GEAR_GRINDER: "Grinder",
    GEAR_ADVANTAGE_S: "Advantage-S",
    GEAR_ADVANTAGE_F: "Advantage-F",
    GEAR_ADVANTAGE_P: "Advantage-P",
    GEAR_CANNONBALL: "Cannonball"
}
ALL_GEARS = list(GEAR_ID_TO_NAME.keys())